# /root/Attempt-2_alpine-with-routinator-installed/docker-compose.yml
services:
  routinator:
    build: .
    container_name: routinator
    network_mode: "host"
    volumes:
      - ./routinator_config_store/routinator.conf:/root/.routinator.conf
      - ./routinator_config_store/certs:/etc/routinator:ro
    restart: unless-stopped
